name: Fallout tests
description: Check Fallout script data and messages for validity
branding:
  icon: message-circle
  color: green

inputs:
  scripts_h:
    description: scripts.h path
    required: true
  scripts_lst:
    description: scripts.lst path
    default: data/scripts/scripts.lst
    required: true
  scripts_dir:
    description: scripts directory
    required: true
  dialog_dir:
    description: text/english/dialog path
    default: data/text/english/dialog
    required: false

runs:
  using: "composite"
  steps:
    - name: test
      shell: bash
      run: $GITHUB_ACTION_PATH/action.sh
      env:
        INPUT_SCRIPTS_H: ${{ inputs.scripts_h }}
        INPUT_SCRIPTS_LST: ${{ inputs.scripts_lst }}
        INPUT_SCRIPTS_DIR: ${{ inputs.scripts_dir }}
        INPUT_DIALOG_DIR: ${{ inputs.dialog_dir }}
