name: "Lint"

on:
  pull_request:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8

      - name: Ruff
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: ty
        run: uv run ty check
